### PR TITLE
Replace SYSDUMMY1 with VALUES where possible

### PR DESCRIPTION
**Pull request by qtemp**

### CODE REVIEW

**Review by kadler — COMMENTED** [review]
I like the use of `VALUES`, though I don't recall when support for it was added. The first I can find in the docs is the 7.3 reference (prior to that it only shows for use in triggers), though it does work in 7.2 so perhaps it was PTF'd back.

**Comment by qtemp** [comment]
Yes, I think it was some time in 7.2 that I first started using VALUES like that.

What I'm trying to work around is an exit program that checks to see if I have access to a particular table.  In this case my profile hasn't specifically been given access to any of the tables in SYSIBM through that exit program.  So, for me any functions that retrieve system variables using SYSIBM/SYSDUMMY1 result in failure.

Example:
select current_timestamp from sysibm.sysdummy1;

Results in:
SQL State: HY001 Vendor Code: -101 Message: [PWS9801] Function rejected by user exit program xxxxx in xxxxx. Cause . . . . . :   User exit program xxxxx in library xxxxx called for the function and returned an indication that the function should not be done. Recovery  . . . :   Determine why the user exit program rejected the function, correct the problem, and run the function again.

**Comment by kadler** [comment]
>  So, for me any functions that retrieve system variables using SYSIBM/SYSDUMMY1 result in failure.

Oh that's annoying! I think we're probably safe to merge this considering it's supported back to 7.2 and that's already out of support. I'm checking with the SQL developers to see when support was added and will update the docs later as-needed

**Review by kadler — APPROVED** [review]

**Comment by kadler** [comment]
I'm told that this was added for 6.1! Talk about a hidden gem. Considering it's been around that long, I'm not gonna bother mentioning it in the doc.

**Pull request merged**
