### PR TITLE
consolidation of reflection and base and removal DB2 reflector and dialect 

### PR DESCRIPTION
**Pull request by naveen-ram**

### CODE REVIEW

**Comment by kadler** [comment]
There's quite a few whitespace changes and things in this PR. We should probably set up lint rules, reformat everything acorrding to those rules, and have the lint run as part of the PR workflow. This will enforce consistent styling from now on and give us a clean break. If we clean up formatting as we go, it will make this history messier than it needs to be.

**Comment by naveen-ram** [comment]
I have made all the changes based on the pylint output that makes sense to make (removed any errors, added basic docstrings). All of the issues come up in base.py.

**Comment by naveen-ram** [comment]
Fixes #14

**Comment by kadler** [comment]
Can we split this in to a PR that does the linting and one that does the consolidation?

**Comment by kadler** [comment]
This PR was made redundant by #32 and #34

**Pull request closed without merging**
